<?php include_once 'header.php';

 include_once './sign.php';
?>;
<!-- Modal -->
<div class="modal fade modal-open bs-example-modal-sm" id="signInModal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
		<div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	        <h4 class="modal-title">Sign In</h4>
	        <small class="js_or-register-new">OR <a href="register.php">REGISTER NEW ACCOUNT</a></small>
	    </div>
        <div class="modal-body">
            
<div class="row">
    <div class="col-md-12">
        <div class="alert hidden js-login_alert"></div>
    </div>
</div>
<form class="form-horizontal" method="POST" action="https://hashing24.com/authenticate" id="js-authenticate">
    <input type="hidden" name="api_key" value="">
    <input type="hidden" name="ask_pin" value="0">
    <input type="hidden" name="ask_2step" value="0">
    <div class="js-auth_inputs js-auth_login">
        <div class="row form-group">
            <div class="col-md-12">
                <input type="text" class="form-control" name="email" placeholder="Email" />
            </div>
        </div>
        <div class="row form-group signin-password-wrapper">
            <div class="col-md-12">
                <input type="password" class="form-control" name="password" placeholder="Password" />
            </div>
        </div>
    </div>
    <div class="js-auth_inputs js-auth_verification display_none">
        <div class="row form-group">
            <div class="col-md-12">
                <h4>
                    2-Step Verification
                    <a href="#"  class="btn btn-default btn-sm j_cancel-2step">Cancel</a>
                </h4>
                Enter the verification code generated by your mobile application &quot;Google Authenticator&quot;.
            </div>
        </div>
        <div class="row form-group">
            <div class="col-md-12">
              <input type="text" class="form-control" name="verification_code" placeholder="Verification code" />
            </div>
        </div>
    </div>
    <div class="js-pin-block hidden">
        <div class="row form-group">
            <div class="col-md-12">
                <h4>Help us serve you better</h4>
                Create a 4-digit PIN to increase your security level.
            </div>
        </div>
        <div class="row form-group">
            <div class="col-md-12">
                <input type="text" class="form-control" name="pin" placeholder="0000" maxlength="4" pattern="\d{4}" />
            </div>
        </div>
        <div class="row form-group">
            <div class="col-md-12">
                <small class="gray">It is very important to remember your PIN. It can not be changed or restored.</small>
            </div>
        </div>
    </div>
    <div class="row form-group js-signin-recaptcha hidden">
        <div class="col-md-12">
            <div id="authRC" class="g-recaptcha" data-sitekey="6Lf-tzMUAAAAAGtf_pw_wsolTKqAqifJ7MYsqPmT"></div>
        </div>
    </div>
    <div class="row form-group signin-button-wrapper">
        <div class="col-md-12">
            <button type="submit" class="btn btn-primary col-md-12 js-signin" data-loading-text="Loading...">Sign In</button>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <a href="index.php" class="btn btn-link js-reset_password" data-loading-text="Loading..."><small>I can&#39;t access my account</small></a>
        </div>
    </div>
    <div class="js-auth_inputs js-auth_verification display_none">
        <p class="small text-center margin-top-5">Wrong code generated?<br>Solution is <a href="faq.php#q19">here</a>.</p>
    </div>
    <div class="js-auth_inputs js-auth_login">
        <div class="sign-in-divider">
            <span>OR</span>
        </div>
        <div class="sign-in-social">sign in with social account</div>
        <div class="sign-in-social-icons">
            <a class="sign-in-social-icon" href="https://graph.facebook.com/oauth/authorize?state=&amp;scope=email&amp;redirect_uri=https%3A%2F%2Fhashing24.com%2Foauth2%2Ffacebook%2Fcallback&amp;client_id=1947287212159869&amp;response_type=code">
                <span class="fa-stack icon-social icon-fb">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                </span>
            </a>
            <a class="sign-in-social-icon" href="https://accounts.google.com/o/oauth2/auth?response_type=code&amp;client_id=943004047393-oqqtc94hmntmej4ivvr25anb57j17lmc.apps.googleusercontent.com&amp;redirect_uri=https%3A%2F%2Fhashing24.com%2Foauth2%2Fgoogle%2Fcallback&amp;scope=email&amp;state=">
                <span class="fa-stack icon-social icon-gp">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-google-plus fa-stack-1x fa-inverse"></i>
                </span>
            </a>
        </div>
    </div>
</form>


<script type="text/javascript">

function preShowCaptcha() {
    $.ajax({
        type: "POST",
        url: '/loginnc'
    })
    .done(function(data) {
        if (data.captcha_is_needed) {
            $('.js-signin-recaptcha').removeClass('hidden');
//            if (grecaptcha && typeof(RCids['authRC']) != 'undefined') {
//                grecaptcha.execute(RCids['authRC']);
//            }
        }
    });
}

$(document).ready(function() {
        $(".js-auth_verification").hide();
        $('.js-pin-block').addClass('hidden');
        $(".js-auth_login").show();
        $(".js-signin").html('Sign In');
        $(".js-login_alert").addClass('hidden');
        $(".js-login_alert").removeClass('alert-danger');
        $(".js-login_alert").removeClass('alert-info');
        $("input[name=email]").focus();
});

var isAuthSubmitting = false;
$("#js-authenticate").submit( function() {
    if (isAuthSubmitting) {
        return false;
    }

    if (!$('.js-pin-block').hasClass('hidden') && $('[name="agreement_external_system"]').length) {
        var stopSubmit = false;
        if ( !$('[name="agreement_external_system"]').prop('checked') ) {
            $('.j_agreement-external-system').addClass('has-error');
            stopSubmit = true;
        }

        if ( !$('[name="disclaimer_external_system"]').prop('checked') ) {
            $('.j_disclaimer-external-system').addClass('has-error');
            stopSubmit = true;
        }

        if (stopSubmit) { return false; }
    }

    isAuthSubmitting = true;
    $(".js-login_alert").addClass('hidden');
    $(".js-login_alert").removeClass('alert-danger');

    $.ajax({
        type: "POST",
        url: '/authenticate',
        data: $('#js-authenticate').serialize(),
    })
    .done(function(data) {
        isAuthSubmitting = false;

        if (data.is_pin_added && typeof(ga) != 'undefined' ) {
            ga('send', 'event', 'REGISTER', 'REGISTER', 'REGISTER');
        }

        if (data.captcha_is_needed) {
            $('.js-signin-recaptcha').removeClass('hidden');
        }
        if (data.error_message || data.captcha_is_needed) {
            if (grecaptcha && typeof(RCids['authRC']) != 'undefined') {
                grecaptcha.reset(RCids['authRC']);
//                grecaptcha.execute(RCids['authRC']);
            }
            if (data.verification_code_error) {
                $("input[name=verification_code]").val('').focus();
            } else {
                $(".js-auth_verification").hide();
                if (!data.pin_error) {
                    $(".js-auth_login").show();
                    $(".js-signin").html('Sign In');
                    $("input[name=password]").val('').focus();
                }
            }
            $(".js-login_alert").addClass('alert-danger');
            $(".js-login_alert").html(data.error_message);
            if (data.error_message) { $(".js-login_alert").removeClass('hidden'); }
        }
        else {
            if (data.google_auth) {
                $('.js-signin-recaptcha').addClass('hidden');
                $(".js_or-register-new").hide();
                $(".js-reset_password").hide();
                //$(".js-auth_inputs").toggle();
                $(".js-auth_login").hide();
                $(".js-auth_verification").show();
                $(".js-signin").html('Verify');
                $("input[name=verification_code]").focus();
                return false;
            }

            if (data.pin_is_needed) {
                $(".js-auth_inputs, .js_or-register-new").hide();
                $(".js-reset_password").hide();
                $('.js-pin-block').removeClass('hidden');
                $(".js-signin").html('Complete registration');
                return false;
            }

            $('#signInModal').hide();
            if (data.redirect_url) {
                document.location.assign(data.redirect_url);
            }
            else {
                if ($('#js-order_form').get(0) && (document.location.pathname == '/' || document.location.pathname == '')) {
                    $ghs = $('input[name=ghs]').val();
                    $currency = $('input[name=currency]:checked').val().toLowerCase();
                    document.location.assign('/portfolio/' + $ghs + '/' + $currency);
                }
                else {
                    if ( data.has_plans ) {
                        document.location.assign('/contract');
                    }
                    else {
                            document.location.assign('/portfolio');
                    }
                }
            }
        }
    })
    .always(function () {
        isAuthSubmitting = false;
        // btn.button('reset')
    });

    return false;
});

$(".js-reset_password").click( function() {
    if ( !$('#js-authenticate').hasClass('js_reseting-password') ) {
        $('#js-authenticate').addClass('js_reseting-password')
//        $('.js-signin-recaptcha').removeClass('hidden');
//        $(".js-reset_password").removeClass('btn-link').addClass('btn btn-danger col-md-12');
    }
    else {
        var la = $(".js-login_alert");
        la.removeClass('alert-danger').addClass('alert-info').html('Checking...').removeClass('hidden');

        $.ajax({
            type: "POST",
            url: '/forgot_password',
            data: $('#js-authenticate').serialize()
        })
        .done(function(data) {
            if (data.message) {
                la.addClass('alert-info').html(data.message).removeClass('hidden');
                $('#js-authenticate').removeClass('js_reseting-password');
            }
            else if (data.error_message) {
                la.addClass('alert-danger').html(data.error_message).removeClass('hidden');
                $('input[name=email]').focus();
            }
        })
        .always(function () {
            // btn.button('reset')
        });
    }
	return false;
});

$('.j_cancel-2step').on('click', function(e){
    $('input[name="ask_2step"]').val(0);
    $(".js-auth_verification").hide();
    $('.js-pin-block').addClass('hidden');
    $(".js-auth_login").show();
    $(".js-signin").html('Sign In');
    $(".js-login_alert").addClass('hidden');
    $(".js-login_alert").removeClass('alert-danger');
    $(".js-login_alert").removeClass('alert-info');
    $(".js_or-register-new").show();
    $(".js-reset_password").show();
    $("input[name=email]").focus();
    return false;
});

</script>

	 	</div>
    </div>
  </div>
</div>

<script>

$('#signInModal').on('shown.bs.modal', function (e) {
    $('#js-authenticate').removeClass('js_reseting-password');
    $("input[name=email]").focus();
        preShowCaptcha();
});

var user_balances = new Array();


$(document).ready(function() {

    $.cookie("tm", (0-(new Date()).getTimezoneOffset()), { expires : 365 });
});

function isBreakpoint( alias ) {
	return $('.device-' + alias).is(':visible');
}

var waitForFinalEvent=function(){var b={};return function(c,d,a){a||(a="");b[a]&&clearTimeout(b[a]);b[a]=setTimeout(c,d)}}();
var fullDateString = new Date();


</script>
<!-- END .header -->


                





                

                <div class="bordered-top"></div>
                <div class="container">
                        <div class="forced-client-menu">
                        
                        </div>
                            



                </div>

                <div class="faq-block-gray">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <h1 class="margin-bottom-15">Frequently Asked Questions</h1>
                <p class="f18">Below are some of the most common questions about Hashing24.</p>
            </div>
        </div>
    </div>
</div>
<div class="page-block-wrapper">
    <div class="container">
        <div class="faq-controls">
            <div class="faq-control j_faq-toggle-all">
                <span class="faq-control-label-open">Open all</span>
                <span class="faq-control-label-close">Close all</span>
            </div>
        </div>
        <div class="faq-block" id="q1">
            <div class="faq-block-title">What is Hashing24?</div>
            <div class="faq-block-desc">    
                <p>Hashing24 offers bitcoin mining without buying any equipment. Instead of it you are buying mining hashpower from our industrial mining equipment supplier BitFury with its data centers located in Iceland and Georgia.</p>
                <p>Hashing24 was created to allow professionals and newcomers similar access to the same quality resources as the industrial miners to allow effective mining. Our cooperation with the industry leaders and access to the newest and most advanced technologies in the industry, quickly made us one of the world‘s leading cloud mining services.</p>
                <p>As a Hashing24 customer, you can enjoy many benefits, including:</p>
                <ul>
                    <li>Access to the world-class data centers and network boasting more than 200 PH/s</li>
                    <li>Instant access to your newly mined bitcoins (within 24 hours)</li>
                    <li>Automatic deposit of mined bitcoins to the balance</li>
                </ul>
</div>
        </div>
        <div class="faq-block" id="q2">
            <div class="faq-block-title">How does bitcoin mining work on your platform?</div>
            <div class="faq-block-desc">    
                <p>It’s pretty quick and easy. As soon as we receive a payment for your order, your contract will be added to your profile. Your order consists of two parts:</p>
                <ul>
                    <li>one-time payment (<b>not deposit</b>) for allocation of ordered power (min order is 100 GH/s, and you can make several orders)</li>
                    <li>a daily maintenance fee for the equipment maintenance and its power supply</li>
                </ul>
                <p>When you are paying <b>one-time payment</b>, you are receiving hashpower according to your contract terms and duration. You will also pay an everyday maintenance fee. This cost is paid in USD, and deducted automatically from the mined volume of BTC, using current exchange rate BTC/USD. Thus, everyday cost for the maintenance in BTC depends on the exchange rate BTC/USD. If you don’t have enough balance during three days to cover your daily maintenance fee, the mining contract and service will be canceled.</p>
</div>
        </div>
        <div class="faq-block" id="q3">
            <div class="faq-block-title">How much profit can I make?</div>
            <div class="faq-block-desc">    
                <p>Earning per day in BTC depends on many factors, such as Block reward, Difficulty, Blocks mined etc and they can’t be predicted. Please note that our payout is based on overall network hashrate, and 100% uptime is guaranteed. We recommend all our clients to do their own research and their own earning calculation, however, we have some helpful tools for this. You can go to the “calculator” tab which is on the top of our website to see how you can calculate your earnings. All the mined bitcoins will be automatically added to your balance.</p>
</div>
        </div>
        <div class="faq-block" id="q4">
            <div class="faq-block-title">What does 100% uptime guarantee mean?</div>
            <div class="faq-block-desc">    
                <p>If you were an individual miner there would be always a possibility that your mining hardware could crash, slow down or completely break. Using our platform you will never happen to face any issues like these.</p>
</div>
        </div>
        <div class="faq-block" id="q5">
            <div class="faq-block-title">How can I pay?</div>
            <div class="faq-block-desc"><ol> <li>Bitcoins: you can buy Bitcoin on any online exchanger: <a target="_blank" href="https://www.buybitcoinworldwide.com/">https://www.buybitcoinworldwide.com/</a>, <a target="_blank" href="https://howtobuybitcoins.info/"> https://howtobuybitcoins.info/</a></li> <li>Visa/Mastercard</li> <li>Bank wire transfer</li> </ol>
</div>
        </div>
        <div class="faq-block" id="q6">
            <div class="faq-block-title">What is maintenance fee?</div>
            <div class="faq-block-desc">    
                <p>The maintenance fee covers all costs related to mining including, inter alia:</p>
                <ul>
                    <li>electricity cost</li>
                    <li>cooling systems</li>
                    <li>maintenance work</li>
                    <li>hosting services</li>
                </ul>
</div>
        </div>
        <div class="faq-block" id="q7">
            <div class="faq-block-title">How often will I receive my profit?</div>
            <div class="faq-block-desc"><p>Newly mined bitcoins are credited to your balance once per day for the previous mining day.</p><p> Our minimum withdrawal amount is 0.002 BTC. You can request a withdrawal any time.</p>
</div>
        </div>
        <div class="faq-block" id="q8">
            <div class="faq-block-title">How can I get in touch with you if I need help?</div>
            <div class="faq-block-desc">    
                <p>Please contact us at: <a href="mailto:support@hashing24.com">support@hashing24.com</a> or simply fill out this form:<br>
                <a href="support.php">https://hashing24.com/support</a></p>
</div>
        </div>
        <div class="faq-block" id="q9">
            <div class="faq-block-title">When does mining start?</div>
            <div class="faq-block-desc"> <p>Mining starts automatically at 00:00 UTC. Mined Bitcoins are credited automatically to the customer’s balance once a day for the previous mining day.</p></div>
        </div>
        <div class="faq-block" id="q10">
            <div class="faq-block-title">How to restore the password?</div>
            <div class="faq-block-desc">    
                <p>In order to restore your password, please:</p>
                <ul>
                    <li>Click on the Sign In</li>
                    <li>Enter your email</li>
                    <li>Click on the "I can't access my account"</li>
                    <li>You will receive an email with further step by step instructions</li>
                </ul>
</div>
        </div>
        <div class="faq-block" id="q11">
            <div class="faq-block-title">How do I withdraw?</div>
            <div class="faq-block-desc">    <p>In order to make a withdrawal:</p> <ul> <li>Sign In to your account</li> <li>Click on the "Withdraw" tab</li> <li>Choose type of coins</li> <li>Enter amount</li> <li>Choose your wallet (or enter new wallet)</li> <li>Click on the withdraw button</li> <li>Check your email inbox, you will receive an email with confirmation link</li> <li>Click on the confirmation link</li> <li>Our minimum withdrawal amount is 0.002 BTC. You can request a withdrawal any time. Withdrawal requests are processed the next day after the request has been placed (UTC time)</li> </ul></div>
        </div>
        <div class="faq-block" id="q12">
            <div class="faq-block-title">How to disable 2-step authentication?</div>
            <div class="faq-block-desc">    
                <p>We can disable your 2-step authentication. Please follow the instructions below:</p>
                <ul>
                    <li>Click on this link: <a href="support.php">https://hashing24.com/support</a></li>
                    <li>Enter your first and last name, email</li>
                    <li>Enter your PIN code in the message field (PIN code that you generated during the registration)</li>
                    <li>Click on the "Submit"</li>
                    <li>We will receive your request and after checking your PIN code we will disable your 2-step authentication</li>
                </ul>
</div>
        </div>
        <div class="faq-block" id="q13">
            <div class="faq-block-title">Which bitcoins do I receive for mining?</div>
            <div class="faq-block-desc">We can guarantee that you will receive only new bitcoins, which have been recently mined. This can be checked on <a href="https://blockchain.info/" target="_blank">blockchain.info</a> by putting in the transaction that you receive after your withdrawal from our service. Thus, everyone can be confident that we are indeed mining bitcoins and we are not some ponzi scheme.

</div>
        </div>
        <div class="faq-block" id="q14">
            <div class="faq-block-title">Why does my withdrawal transaction have many different wallet addresses?
</div>
            <div class="faq-block-desc">The clients' transactions are grouped together for withdrawal to optimise and increase the speed of transactions.
</div>
        </div>
        <div class="faq-block" id="q16">
            <div class="faq-block-title">What do I do if I paid the money for the contract but it hasn't been activated?
</div>
            <div class="faq-block-desc"><ul>
<li> Sign In to your account</li>
<li>Choose plan on this page: <a href="tariffs.php">https://hashing24.com/tariffs</a> </li>
<li>Choose price in BTC/USD/EUR</li> 
<li>Click on the "Buy" button</li> 
<li>Check details of your order and click on the "Next Step" button</li>
<li> Choose the payment method that you used previously and click “Buy”</li> 
<li>Your plan will be purchased using your current balance</li>  
</ul> 
<p> P.S. You don’t need to pay again, you will just use the balance that you have on your account.</p></div>
        </div>
        <div class="faq-block" id="q17">
            <div class="faq-block-title">What does the payout amount depend on?</div>
            <div class="faq-block-desc">The number of bitcoins that can be mined and circulated is limited. The more bitcoins are being mined, the higher mining difficulty gets increased, which requires an additional time for mining. The amount of bitcoins that are credited to the balance is also influenced by the BTC/USD exchange rate, as the maintenance cost of the contract is paid in USD and we’ll need to sell some part of mined bitcoins due to the Coindesk BPI daily closing price for its covering. Thus, the higher the BTC price, the less you need to pay for the maintenance and the higher is the payout from the contract.</div>
        </div>
        <div class="faq-block" id="q18">
            <div class="faq-block-title">What is 'Reinvestment'? How do I use it?
</div>
            <div class="faq-block-desc">The “Reinvestment" function allows you to buy additional mining hashpower, using the mined coins that you have on your balance.</br>Once you click on “Reinvestment” button, the order for the maximum allowed contract volume will be placed automatically. You will just need to check the details of this order and click on “Pay” button. The payment will be done from your Hashing24 account balance.

</div>
        </div>
        <div class="faq-block" id="q19">
            <div class="faq-block-title">What to do if 2-step code is not working?</div>
            <div class="faq-block-desc"><p>This might be because the time on your Google Authenticator app is not synchronize correctly. To make sure that you have the correct time:</p>
<ol>
<li>Go to the main menu in the Google Authenticator app</li>
<li>Click Settings</li>
<li>Click Time Correction for codes</li>
<li>Click "Sync now"</li>
</ol>
<p>The app will confirm that the time has been synced, and you should now be able to use your verification codes to sign in. The synchronization will only affect the internal time of your Google Authenticator app and will not change your device’s Date & time settings.</p></div>
        </div>
    </div>
</div>

<script>
$('.faq-block-title').on('click', function(){
    $(this).closest('.faq-block').toggleClass('faq-block-expanded');
});

$('.j_faq-toggle-all').on('click', function(){
    var $self = $(this);
    $self.toggleClass('faq-control-expanded');
    $('.faq-block').toggleClass('faq-block-expanded', $self.hasClass('faq-control-expanded'));
});

var qMatches = location.hash.match(new RegExp('(q\\d+)'));
if(qMatches) {
    var qID = qMatches[1];
    $('#'+qID+'.faq-block').toggleClass('faq-block-expanded');
}

</script>


            </div>
            


<div class="modal fade modal-open" id="maintenanceModal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title">Current Maintenance Cost</h4>
        </div>
        <div class="modal-body margin-bottom-0 padding-bottom-0">
            <div class="row">
                <div class="col-md-12">
                    To cover electricity use and system upkeep, we charge a small commission for cloud-based THS.
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <h2 class="margin-bottom-0 padding-bottom-0">1 THS maintenance = $
                        <button class="btn btn-default btn-lg" disabled><b>0.33</b></button>
                        <small class="black">per day</small>
                    </h2>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <div class="text-left">
            Find detailed information on how the cost is covered and calculated in our terms of use <a href="terms.php">here</a>.
            <button type="button" class="btn btn-default pull-right" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
  </div>
</div>



<?php include_once 'footer.php';?>
        <div class='notifications top-right'></div>
        <script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','../www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-78502902-1', 'auto');
  ga('send', 'pageview');



</script>

<!-- Yandex.Metrika counter -->
<script type="text/javascript">
    (function (d, w, c) {
        (w[c] = w[c] || []).push(function() {
            try {
                w.yaCounter37629880 = new Ya.Metrika({
                    id:37629880,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true,
                    webvisor:true
                });
            } catch(e) { }
        });

        var n = d.getElementsByTagName("script")[0],
            s = d.createElement("script"),
            f = function () { n.parentNode.insertBefore(s, n); };
        s.type = "text/javascript";
        s.async = true;
        s.src = "../d31j93rd8oukbv.cloudfront.net/metrika/watch_ua.js";

        if (w.opera == "[object Opera]") {
            d.addEventListener("DOMContentLoaded", f, false);
        } else { f(); }
    })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/37629880" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->

        <script type="text/javascript">
window.__lc = window.__lc || {};
window.__lc.license = 8095831;
(function() {
var lc = document.createElement('script'); lc.type = 'text/javascript'; lc.async = true;
lc.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'cdn.livechatinc.com/tracking.js';
var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(lc, s);
})();
</script>


    </body>

<!-- Mirrored from hashing24.com/faq by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 10 Dec 2017 16:48:02 GMT -->
</html>
